# Generated by Django 5.0.1 on 2025-01-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(default='Kimani Kimanongo'),
        ),
    ]
